//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Products = new HashSet<Product>();
            this.Balances = new HashSet<Balance>();
            this.Sales = new HashSet<Sale>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Descr { get; set; }
        public bool Disabled { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Balance> Balances { get; set; }
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
