//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Descr { get; set; }
        public string Addr { get; set; }
        public System.DateTime Opened { get; set; }
        public Nullable<System.DateTime> Closed { get; set; }
    }
}
