
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ShopManagment
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
public partial class Storage
{

    public Storage()
    {

        this.Balances = new HashSet<Balance>();

        this.Sales = new HashSet<Sale>();

    }


    public int ID { get; set; }
    [Required(AllowEmptyStrings = true)]
    [DisplayFormat(ConvertEmptyStringToNull = false)]
    public string Name { get; set; }

    public string Descr { get; set; }

    public string Addr { get; set; }

    public System.DateTime Opened { get; set; }

    public Nullable<System.DateTime> Closed { get; set; }



    public virtual ICollection<Balance> Balances { get; set; }

    public virtual ICollection<Sale> Sales { get; set; }

}

}
